config/routes.rb
Rails.application.routes.draw do

  devise_for :members

  resources :members do
  	 resources :profiles
  	 resources :localtions
  end
  
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/localtion.rb
class Localtion < ApplicationRecord
	validates_presence_of :name, :address_1, :address_2, :city, :region, :zip_code, :country, :description
	validates_presence_of :member_id

	belongs_to :member, optional: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates_presence_of  :name
   
   has_one :profile
   has_many :localtion
end

app/models/profile.rb
class Profile < ApplicationRecord
	validates_presence_of :bio
	validates_presence_of :member_id

	belongs_to :member, optional: true

	has_attached_file :profile_pic, styles: { small: "100x100#" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :profile_pic, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  alias_method :current_user, :current_member

  rescue_from Pundit::NotAuthorizedError, with: :member_not_authorized

  private

  	def member_not_authorized
  		flash[:alert] = "You are authorized to perform this action."

  		redirect to(request.referrer || root_path)
  		
  	end
  	
  protected

  	def configure_permitted_parameters
  	#	devise_parameter_sanitizer.for(:sign_up) << :name
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/localtions_controller.rb
class LocaltionsController < ApplicationController
  before_action :set_localtion, only: [:show, :edit, :update, :destroy]
  before_action :set_member
  before_action :authenticate_member!

  def index
    authorize @localtion
    @localtion = Localtion.all
  end

  def show
    authorize @localtion
  end

  def new
  	@localtion = @member.build_profile
    authorize @localtion
  end

  def edit
    authorize @localtion
  end

  def create
    @localtion = @member.create_localtion(localtion_params)
    authorize @localtion

    respond_to do |format|
      if @localtion.save
        format.html { redirect_to member_localtion_path(@member, @localtion), notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @localtion }
      else
        format.html { render :new }
        format.json { render json: @localtion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_localtion
      @localtion = Localtion.find(params[:id])
    end

    def set_member
      @member = Member.find(params[:member_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def localtion_params
      params.require(:localtion).permit(:name, :address_1, :address_2, :city, :region, :zip_code, :country, :description, :member_id)
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :set_member
  before_action :authenticate_member!

  # GET /profiles
  # GET /profiles.json
  def index
    authorize @profile
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    authorize @profile
  end

  # GET /profiles/new
  def new
    @profile = @member.build_profile
    authorize @profile
  end

  # GET /profiles/1/edit
  def edit
    authorize @profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = @member.create_profile(profile_params)
    authorize @profile

    respond_to do |format|
      if @profile.save
        format.html { redirect_to member_profile_path(@member, @profile), notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    authorize @profile
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    authorize @profile
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def set_member
      @member = Member.find(params[:member_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:bio, :member_id, :profile_pic)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/localtions_helper.rb
module LocaltionsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<p>Welcome to Better Than AirBnB</p>

<%= link_to "Become A Host", new_member_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseSkeleton</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if member_signed_in? %>
      <%= render "shared/logged_out_header" %>
    <% else %>
      <%= render "shared/logged_in_header" %>
    <% end %>

    <% unless notice.blank? %>
      <%= notice %>
    <% end %>
    <% unless alert.blank? %>
      <%= alert %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/localtions/_form.html.erb
<%= form_with(scope: :localtion, url: member_localtions_path ) do |f| %>
  <% if localtion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(localtion.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% localtion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :address_1 %>
    <%= f.text_field :address_1, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :address_2 %>
    <%= f.text_field :address_2, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :region %>
    <%= f.text_field :region, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.country_select :country, {priority: %w(US CA), prompt: 'Please select a country'} %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Create Location" %>
  </div>
<% end %>

app/views/localtions/edit.html.erb
<h1>Localtions#edit</h1>
<p>Find me in app/views/localtions/edit.html.erb</p>

app/views/localtions/index.html.erb
<h1>Localtions#index</h1>
<p>Find me in app/views/localtions/index.html.erb</p>

app/views/localtions/new.html.erb
<h1>New Location</h1>

<%= render 'form', localtion: @localtion %>

app/views/localtions/update.html.erb
<h1>Localtions#update</h1>
<p>Find me in app/views/localtions/update.html.erb</p>

app/views/profiles/_form.html.erb
<%= form_with(scope: :profile, url: member_profiles_path ) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.file_field :profile_pic %>
  </div>

  <div class="actions">
    <%= f.submit "Create Profile" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Bio</th>
      <th>Member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.bio %></td>
        <td><%= profile.member_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<p>
  <strong>Member:</strong>
  <%= @profile.member_id %>
</p>

app/views/shared/_logged_in_header.html.erb
<%= link_to "Log in", new_member_session_path %>

app/views/shared/_logged_out_header.html.erb
<%= link_to "Sign out", destroy_member_session_path, method: :delete %>